-- XXL-JOB 2.4.1 PostgreSQL 16 fresh initialization.
-- Target: test_db, schema app.
-- Before execution, confirm that schema app exists and no app.xxl_job_* table exists.
-- This script does not modify unrelated objects such as app.test_tb.
-- Run the whole script in one session; execute ROLLBACK if an error occurs.

BEGIN;

SET LOCAL search_path TO app;

CREATE TABLE xxl_job_info (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    job_group integer NOT NULL,
    job_desc varchar(255) NOT NULL,
    add_time timestamp,
    update_time timestamp,
    author varchar(64),
    alarm_email varchar(255),
    schedule_type varchar(50) NOT NULL DEFAULT 'NONE',
    schedule_conf varchar(128),
    misfire_strategy varchar(50) NOT NULL DEFAULT 'DO_NOTHING',
    executor_route_strategy varchar(50),
    executor_handler varchar(255),
    executor_param varchar(512),
    executor_block_strategy varchar(50),
    executor_timeout integer NOT NULL DEFAULT 0,
    executor_fail_retry_count integer NOT NULL DEFAULT 0,
    glue_type varchar(50) NOT NULL,
    glue_source text,
    glue_remark varchar(128),
    glue_updatetime timestamp,
    child_jobid varchar(255),
    trigger_status smallint NOT NULL DEFAULT 0,
    trigger_last_time bigint NOT NULL DEFAULT 0,
    trigger_next_time bigint NOT NULL DEFAULT 0,
    CONSTRAINT pk_xxljobinfo PRIMARY KEY (id)
);

COMMENT ON TABLE xxl_job_info IS 'XXL-JOB task information';
COMMENT ON COLUMN xxl_job_info.job_group IS 'Executor primary key ID';
COMMENT ON COLUMN xxl_job_info.author IS 'Author';
COMMENT ON COLUMN xxl_job_info.alarm_email IS 'Alarm email';
COMMENT ON COLUMN xxl_job_info.schedule_type IS 'Schedule type';
COMMENT ON COLUMN xxl_job_info.schedule_conf IS 'Schedule configuration';
COMMENT ON COLUMN xxl_job_info.misfire_strategy IS 'Schedule misfire strategy';
COMMENT ON COLUMN xxl_job_info.executor_route_strategy IS 'Executor route strategy';
COMMENT ON COLUMN xxl_job_info.executor_handler IS 'Executor job handler';
COMMENT ON COLUMN xxl_job_info.executor_param IS 'Executor parameter';
COMMENT ON COLUMN xxl_job_info.executor_block_strategy IS 'Executor block strategy';
COMMENT ON COLUMN xxl_job_info.executor_timeout IS 'Execution timeout in seconds';
COMMENT ON COLUMN xxl_job_info.executor_fail_retry_count IS 'Failure retry count';
COMMENT ON COLUMN xxl_job_info.glue_type IS 'GLUE type';
COMMENT ON COLUMN xxl_job_info.glue_source IS 'GLUE source';
COMMENT ON COLUMN xxl_job_info.glue_remark IS 'GLUE remark';
COMMENT ON COLUMN xxl_job_info.glue_updatetime IS 'GLUE update time';
COMMENT ON COLUMN xxl_job_info.child_jobid IS 'Comma-separated child job IDs';
COMMENT ON COLUMN xxl_job_info.trigger_status IS 'Schedule status: 0 stopped, 1 running';
COMMENT ON COLUMN xxl_job_info.trigger_last_time IS 'Previous trigger epoch milliseconds';
COMMENT ON COLUMN xxl_job_info.trigger_next_time IS 'Next trigger epoch milliseconds';

CREATE TABLE xxl_job_log (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    job_group integer NOT NULL,
    job_id integer NOT NULL,
    executor_address varchar(255),
    executor_handler varchar(255),
    executor_param varchar(512),
    executor_sharding_param varchar(20),
    executor_fail_retry_count integer NOT NULL DEFAULT 0,
    trigger_time timestamp,
    trigger_code integer NOT NULL,
    trigger_msg text,
    handle_time timestamp,
    handle_code integer NOT NULL,
    handle_msg text,
    alarm_status smallint NOT NULL DEFAULT 0,
    CONSTRAINT pk_xxljoblog PRIMARY KEY (id)
);

COMMENT ON TABLE xxl_job_log IS 'XXL-JOB execution log';
COMMENT ON COLUMN xxl_job_log.job_group IS 'Executor primary key ID';
COMMENT ON COLUMN xxl_job_log.job_id IS 'Task primary key ID';
COMMENT ON COLUMN xxl_job_log.executor_address IS 'Executor address';
COMMENT ON COLUMN xxl_job_log.executor_handler IS 'Executor job handler';
COMMENT ON COLUMN xxl_job_log.executor_param IS 'Executor parameter';
COMMENT ON COLUMN xxl_job_log.executor_sharding_param IS 'Sharding parameter in index/total format';
COMMENT ON COLUMN xxl_job_log.executor_fail_retry_count IS 'Failure retry count';
COMMENT ON COLUMN xxl_job_log.trigger_time IS 'Trigger time without time zone';
COMMENT ON COLUMN xxl_job_log.trigger_code IS 'Trigger result code';
COMMENT ON COLUMN xxl_job_log.trigger_msg IS 'Trigger message';
COMMENT ON COLUMN xxl_job_log.handle_time IS 'Handle time without time zone';
COMMENT ON COLUMN xxl_job_log.handle_code IS 'Handle result code';
COMMENT ON COLUMN xxl_job_log.handle_msg IS 'Handle message';
COMMENT ON COLUMN xxl_job_log.alarm_status IS 'Alarm status: 0 default, 1 ignored, 2 success, 3 failure';

CREATE INDEX IF NOT EXISTS idx_xxljoblog_triggertime
    ON xxl_job_log (trigger_time);

CREATE INDEX IF NOT EXISTS idx_xxljoblog_handlecode
    ON xxl_job_log (handle_code);

CREATE TABLE xxl_job_log_report (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    trigger_day timestamp,
    running_count integer NOT NULL DEFAULT 0,
    suc_count integer NOT NULL DEFAULT 0,
    fail_count integer NOT NULL DEFAULT 0,
    update_time timestamp,
    CONSTRAINT pk_xxljoblogreport PRIMARY KEY (id)
);

COMMENT ON TABLE xxl_job_log_report IS 'XXL-JOB daily log report';
COMMENT ON COLUMN xxl_job_log_report.trigger_day IS 'Report day without time zone';
COMMENT ON COLUMN xxl_job_log_report.running_count IS 'Running log count';
COMMENT ON COLUMN xxl_job_log_report.suc_count IS 'Successful log count';
COMMENT ON COLUMN xxl_job_log_report.fail_count IS 'Failed log count';

CREATE UNIQUE INDEX IF NOT EXISTS uk_xxljoblogreport_triggerday
    ON xxl_job_log_report (trigger_day);

CREATE TABLE xxl_job_logglue (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    job_id integer NOT NULL,
    glue_type varchar(50),
    glue_source text,
    glue_remark varchar(128) NOT NULL,
    add_time timestamp,
    update_time timestamp,
    CONSTRAINT pk_xxljoblogglue PRIMARY KEY (id)
);

COMMENT ON TABLE xxl_job_logglue IS 'XXL-JOB GLUE change history';
COMMENT ON COLUMN xxl_job_logglue.job_id IS 'Task primary key ID';
COMMENT ON COLUMN xxl_job_logglue.glue_type IS 'GLUE type';
COMMENT ON COLUMN xxl_job_logglue.glue_source IS 'GLUE source';
COMMENT ON COLUMN xxl_job_logglue.glue_remark IS 'GLUE remark';

CREATE TABLE xxl_job_registry (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    registry_group varchar(50) NOT NULL,
    registry_key varchar(255) NOT NULL,
    registry_value varchar(255) NOT NULL,
    update_time timestamp,
    CONSTRAINT pk_xxljobregistry PRIMARY KEY (id)
);

COMMENT ON TABLE xxl_job_registry IS 'XXL-JOB executor registry';

CREATE INDEX IF NOT EXISTS idx_xxljobregistry_registrygroup_registrykey_registryvalue
    ON xxl_job_registry (registry_group, registry_key, registry_value);

CREATE TABLE xxl_job_group (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    app_name varchar(64) NOT NULL,
    title varchar(12) NOT NULL,
    address_type smallint NOT NULL DEFAULT 0,
    address_list text,
    update_time timestamp,
    CONSTRAINT pk_xxljobgroup PRIMARY KEY (id)
);

COMMENT ON TABLE xxl_job_group IS 'XXL-JOB executor group';
COMMENT ON COLUMN xxl_job_group.app_name IS 'Executor AppName';
COMMENT ON COLUMN xxl_job_group.title IS 'Executor name';
COMMENT ON COLUMN xxl_job_group.address_type IS 'Address type: 0 automatic, 1 manual';
COMMENT ON COLUMN xxl_job_group.address_list IS 'Comma-separated executor addresses';

CREATE TABLE xxl_job_user (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    username varchar(50) NOT NULL,
    password varchar(50) NOT NULL,
    role smallint NOT NULL,
    permission varchar(255),
    CONSTRAINT pk_xxljobuser PRIMARY KEY (id)
);

COMMENT ON TABLE xxl_job_user IS 'XXL-JOB user';
COMMENT ON COLUMN xxl_job_user.username IS 'Account';
COMMENT ON COLUMN xxl_job_user.password IS 'Password hash';
COMMENT ON COLUMN xxl_job_user.role IS 'Role: 0 regular user, 1 administrator';
COMMENT ON COLUMN xxl_job_user.permission IS 'Comma-separated executor group IDs';

CREATE UNIQUE INDEX IF NOT EXISTS uk_xxljobuser_username
    ON xxl_job_user (username);

CREATE TABLE xxl_job_lock (
    lock_name varchar(50) NOT NULL,
    CONSTRAINT pk_xxljoblock PRIMARY KEY (lock_name)
);

COMMENT ON TABLE xxl_job_lock IS 'XXL-JOB scheduler lock';
COMMENT ON COLUMN xxl_job_lock.lock_name IS 'Lock name';

-- Seed data from XXL-JOB 2.4.1.
INSERT INTO xxl_job_group (
    id,
    app_name,
    title,
    address_type,
    address_list,
    update_time
) VALUES (
    1,
    'xxl-job-executor-sample',
    '示例执行器',
    0,
    NULL,
    TIMESTAMP '2018-11-03 22:21:31'
);

INSERT INTO xxl_job_info (
    id,
    job_group,
    job_desc,
    add_time,
    update_time,
    author,
    alarm_email,
    schedule_type,
    schedule_conf,
    misfire_strategy,
    executor_route_strategy,
    executor_handler,
    executor_param,
    executor_block_strategy,
    executor_timeout,
    executor_fail_retry_count,
    glue_type,
    glue_source,
    glue_remark,
    glue_updatetime,
    child_jobid
) VALUES (
    1,
    1,
    '测试任务1',
    TIMESTAMP '2018-11-03 22:21:31',
    TIMESTAMP '2018-11-03 22:21:31',
    'XXL',
    '',
    'CRON',
    '0 0 0 * * ? *',
    'DO_NOTHING',
    'FIRST',
    'demoJobHandler',
    '',
    'SERIAL_EXECUTION',
    0,
    0,
    'BEAN',
    '',
    'GLUE代码初始化',
    TIMESTAMP '2018-11-03 22:21:31',
    ''
);

INSERT INTO xxl_job_user (
    id,
    username,
    password,
    role,
    permission
) VALUES (
    1,
    'admin',
    'e10adc3949ba59abbe56e057f20f883e',
    1,
    NULL
);

INSERT INTO xxl_job_lock (lock_name)
VALUES ('schedule_lock');

-- Fixed seed IDs do not advance identity sequences automatically.
SELECT setval(
    pg_get_serial_sequence('xxl_job_group', 'id'),
    (SELECT max(id) FROM xxl_job_group),
    true
);

SELECT setval(
    pg_get_serial_sequence('xxl_job_info', 'id'),
    (SELECT max(id) FROM xxl_job_info),
    true
);

SELECT setval(
    pg_get_serial_sequence('xxl_job_user', 'id'),
    (SELECT max(id) FROM xxl_job_user),
    true
);

COMMIT;
-- On error, execute: ROLLBACK;
