-- XXL-JOB PostgreSQL 16 全新初始化脚本
-- 模式：app；执行前确认 app 已存在、当前用户可在其中创建对象，且不存在同名 XXL-JOB 表
-- 整段同一事务；报错后同会话执行 ROLLBACK

BEGIN;

CREATE SCHEMA IF NOT EXISTS app;

SET search_path TO app;

CREATE TABLE xxl_job_info
(
    id                        integer GENERATED BY DEFAULT AS IDENTITY,
    job_group                 integer      NOT NULL,
    job_desc                  varchar(255) NOT NULL,
    add_time                  timestamp without time zone,
    update_time               timestamp without time zone,
    author                    varchar(64),
    alarm_email               varchar(255),
    schedule_type             varchar(50)  NOT NULL DEFAULT 'NONE',
    schedule_conf             varchar(128),
    misfire_strategy          varchar(50)  NOT NULL DEFAULT 'DO_NOTHING',
    executor_route_strategy   varchar(50),
    executor_handler          varchar(255),
    executor_param            varchar(512),
    executor_block_strategy   varchar(50),
    executor_timeout          integer      NOT NULL DEFAULT 0,
    executor_fail_retry_count integer      NOT NULL DEFAULT 0,
    glue_type                 varchar(50)  NOT NULL,
    glue_source               text,
    glue_remark               varchar(128),
    glue_updatetime           timestamp without time zone,
    child_jobid               varchar(255),
    trigger_status            smallint     NOT NULL DEFAULT 0,
    trigger_last_time         bigint       NOT NULL DEFAULT 0,
    trigger_next_time         bigint       NOT NULL DEFAULT 0,
    CONSTRAINT pk_xxljobinfo PRIMARY KEY (id)
);

COMMENT ON TABLE xxl_job_info IS '任务信息';
COMMENT ON COLUMN xxl_job_info.job_group IS '执行器主键ID';
COMMENT ON COLUMN xxl_job_info.author IS '作者';
COMMENT ON COLUMN xxl_job_info.alarm_email IS '报警邮件';
COMMENT ON COLUMN xxl_job_info.schedule_type IS '调度类型';
COMMENT ON COLUMN xxl_job_info.schedule_conf IS '调度配置，值含义取决于调度类型';
COMMENT ON COLUMN xxl_job_info.misfire_strategy IS '调度过期策略';
COMMENT ON COLUMN xxl_job_info.executor_route_strategy IS '执行器路由策略';
COMMENT ON COLUMN xxl_job_info.executor_handler IS '执行器任务handler';
COMMENT ON COLUMN xxl_job_info.executor_param IS '执行器任务参数';
COMMENT ON COLUMN xxl_job_info.executor_block_strategy IS '阻塞处理策略';
COMMENT ON COLUMN xxl_job_info.executor_timeout IS '任务执行超时时间，单位秒';
COMMENT ON COLUMN xxl_job_info.executor_fail_retry_count IS '失败重试次数';
COMMENT ON COLUMN xxl_job_info.glue_type IS 'GLUE类型';
COMMENT ON COLUMN xxl_job_info.glue_source IS 'GLUE源代码';
COMMENT ON COLUMN xxl_job_info.glue_remark IS 'GLUE备注';
COMMENT ON COLUMN xxl_job_info.glue_updatetime IS 'GLUE更新时间';
COMMENT ON COLUMN xxl_job_info.child_jobid IS '子任务ID，多个逗号分隔';
COMMENT ON COLUMN xxl_job_info.trigger_status IS '调度状态：0-停止，1-运行';
COMMENT ON COLUMN xxl_job_info.trigger_last_time IS '上次调度时间';
COMMENT ON COLUMN xxl_job_info.trigger_next_time IS '下次调度时间';

CREATE TABLE xxl_job_log
(
    id                        bigint GENERATED BY DEFAULT AS IDENTITY,
    job_group                 integer      NOT NULL,
    job_id                    integer      NOT NULL,
    executor_address          varchar(255),
    executor_handler          varchar(255),
    executor_param            varchar(512),
    executor_sharding_param   varchar(20),
    executor_fail_retry_count integer      NOT NULL DEFAULT 0,
    trigger_time              timestamp without time zone,
    trigger_code              integer      NOT NULL,
    trigger_msg               text,
    handle_time               timestamp without time zone,
    handle_code               integer      NOT NULL,
    handle_msg                text,
    alarm_status              smallint     NOT NULL DEFAULT 0,
    CONSTRAINT pk_xxljoblog PRIMARY KEY (id)
);

COMMENT ON TABLE xxl_job_log IS '任务调度日志';
COMMENT ON COLUMN xxl_job_log.job_group IS '执行器主键ID';
COMMENT ON COLUMN xxl_job_log.job_id IS '任务主键ID';
COMMENT ON COLUMN xxl_job_log.executor_address IS '执行器地址，本次执行的地址';
COMMENT ON COLUMN xxl_job_log.executor_handler IS '执行器任务handler';
COMMENT ON COLUMN xxl_job_log.executor_param IS '执行器任务参数';
COMMENT ON COLUMN xxl_job_log.executor_sharding_param IS '执行器任务分片参数，格式如1/2';
COMMENT ON COLUMN xxl_job_log.executor_fail_retry_count IS '失败重试次数';
COMMENT ON COLUMN xxl_job_log.trigger_time IS '调度时间';
COMMENT ON COLUMN xxl_job_log.trigger_code IS '调度结果';
COMMENT ON COLUMN xxl_job_log.trigger_msg IS '调度日志';
COMMENT ON COLUMN xxl_job_log.handle_time IS '执行时间';
COMMENT ON COLUMN xxl_job_log.handle_code IS '执行状态';
COMMENT ON COLUMN xxl_job_log.handle_msg IS '执行日志';
COMMENT ON COLUMN xxl_job_log.alarm_status IS '告警状态：0-默认、1-无需告警、2-告警成功、3-告警失败';

CREATE INDEX IF NOT EXISTS idx_xxljoblog_triggertime
    ON xxl_job_log (trigger_time);

CREATE INDEX IF NOT EXISTS idx_xxljoblog_handlecode
    ON xxl_job_log (handle_code);

CREATE INDEX IF NOT EXISTS idx_xxljoblog_jobid_jobgroup
    ON xxl_job_log (job_id, job_group);

CREATE INDEX IF NOT EXISTS idx_xxljoblog_jobid
    ON xxl_job_log (job_id);

CREATE TABLE xxl_job_log_report
(
    id            integer GENERATED BY DEFAULT AS IDENTITY,
    trigger_day   timestamp without time zone,
    running_count integer NOT NULL DEFAULT 0,
    suc_count     integer NOT NULL DEFAULT 0,
    fail_count    integer NOT NULL DEFAULT 0,
    update_time   timestamp without time zone,
    CONSTRAINT pk_xxljoblogreport PRIMARY KEY (id)
);

COMMENT ON TABLE xxl_job_log_report IS '任务调度日志报表';
COMMENT ON COLUMN xxl_job_log_report.trigger_day IS '调度时间';
COMMENT ON COLUMN xxl_job_log_report.running_count IS '运行中日志数量';
COMMENT ON COLUMN xxl_job_log_report.suc_count IS '执行成功日志数量';
COMMENT ON COLUMN xxl_job_log_report.fail_count IS '执行失败日志数量';

CREATE UNIQUE INDEX IF NOT EXISTS uk_xxljoblogreport_triggerday
    ON xxl_job_log_report (trigger_day);

CREATE TABLE xxl_job_logglue
(
    id          integer GENERATED BY DEFAULT AS IDENTITY,
    job_id      integer      NOT NULL,
    glue_type   varchar(50),
    glue_source text,
    glue_remark varchar(128) NOT NULL,
    add_time    timestamp without time zone,
    update_time timestamp without time zone,
    CONSTRAINT pk_xxljoblogglue PRIMARY KEY (id)
);

COMMENT ON TABLE xxl_job_logglue IS '任务GLUE代码历史';
COMMENT ON COLUMN xxl_job_logglue.job_id IS '任务主键ID';
COMMENT ON COLUMN xxl_job_logglue.glue_type IS 'GLUE类型';
COMMENT ON COLUMN xxl_job_logglue.glue_source IS 'GLUE源代码';
COMMENT ON COLUMN xxl_job_logglue.glue_remark IS 'GLUE备注';

CREATE TABLE xxl_job_registry
(
    id             integer GENERATED BY DEFAULT AS IDENTITY,
    registry_group varchar(50)  NOT NULL,
    registry_key   varchar(255) NOT NULL,
    registry_value varchar(255) NOT NULL,
    update_time    timestamp without time zone,
    CONSTRAINT pk_xxljobregistry PRIMARY KEY (id)
);

COMMENT ON TABLE xxl_job_registry IS '执行器注册信息';

CREATE UNIQUE INDEX IF NOT EXISTS uk_xxljobregistry_registrygroup_registrykey_registryvalue
    ON xxl_job_registry (registry_group, registry_key, registry_value);

CREATE TABLE xxl_job_group
(
    id           integer GENERATED BY DEFAULT AS IDENTITY,
    app_name     varchar(64) NOT NULL,
    title        varchar(12) NOT NULL,
    address_type smallint    NOT NULL DEFAULT 0,
    address_list text,
    update_time  timestamp without time zone,
    CONSTRAINT pk_xxljobgroup PRIMARY KEY (id)
);

COMMENT ON TABLE xxl_job_group IS '执行器信息';
COMMENT ON COLUMN xxl_job_group.app_name IS '执行器AppName';
COMMENT ON COLUMN xxl_job_group.title IS '执行器名称';
COMMENT ON COLUMN xxl_job_group.address_type IS '执行器地址类型：0-自动注册、1-手动录入';
COMMENT ON COLUMN xxl_job_group.address_list IS '执行器地址列表，多地址逗号分隔';

CREATE TABLE xxl_job_user
(
    id         integer GENERATED BY DEFAULT AS IDENTITY,
    username   varchar(50) NOT NULL,
    password   varchar(50) NOT NULL,
    role       smallint    NOT NULL,
    permission varchar(255),
    CONSTRAINT pk_xxljobuser PRIMARY KEY (id)
);

COMMENT ON TABLE xxl_job_user IS '系统用户';
COMMENT ON COLUMN xxl_job_user.username IS '账号';
COMMENT ON COLUMN xxl_job_user.password IS '密码';
COMMENT ON COLUMN xxl_job_user.role IS '角色：0-普通用户、1-管理员';
COMMENT ON COLUMN xxl_job_user.permission IS '权限：执行器ID列表，多个逗号分隔';

CREATE UNIQUE INDEX IF NOT EXISTS uk_xxljobuser_username
    ON xxl_job_user (username);

CREATE TABLE xxl_job_lock
(
    lock_name varchar(50) NOT NULL,
    CONSTRAINT pk_xxljoblock PRIMARY KEY (lock_name)
);

COMMENT ON TABLE xxl_job_lock IS '调度锁';
COMMENT ON COLUMN xxl_job_lock.lock_name IS '锁名称';

-- 初始化数据
INSERT INTO xxl_job_group (id, app_name, title, address_type, address_list, update_time)
VALUES (1, 'xxl-job-executor-sample', '通用执行器Sample', 0, NULL, now()),
       (2, 'xxl-job-executor-sample-ai', 'AI执行器Sample', 0, NULL, now());

INSERT INTO xxl_job_info (id, job_group, job_desc, add_time, update_time, author, alarm_email,
                          schedule_type, schedule_conf, misfire_strategy, executor_route_strategy,
                          executor_handler, executor_param, executor_block_strategy, executor_timeout,
                          executor_fail_retry_count, glue_type, glue_source, glue_remark, glue_updatetime,
                          child_jobid)
VALUES (1, 1, '示例任务01', now(), now(), 'XXL', '', 'CRON', '0 0 0 * * ? *',
        'DO_NOTHING', 'FIRST', 'demoJobHandler', '', 'SERIAL_EXECUTION', 0, 0, 'BEAN', '', 'GLUE代码初始化',
        now(), ''),
       (2, 2, 'Ollama示例任务01', now(), now(), 'XXL', '', 'NONE', '',
        'DO_NOTHING', 'FIRST', 'ollamaJobHandler', '{
    "input": "慢SQL问题分析思路",
    "prompt": "你是一个研发工程师，擅长解决技术类问题。"
}', 'SERIAL_EXECUTION', 0, 0, 'BEAN', '', 'GLUE代码初始化',
        now(), ''),
       (3, 2, 'Dify示例任务', now(), now(), 'XXL', '', 'NONE', '',
        'DO_NOTHING', 'FIRST', 'difyWorkflowJobHandler', '{
    "inputs": {
        "input": "查询班级各学科前三名"
    },
    "user": "xxl-job"
}', 'SERIAL_EXECUTION', 0, 0, 'BEAN', '', 'GLUE代码初始化',
        now(), '');

INSERT INTO xxl_job_user (id, username, password, role, permission)
VALUES (1, 'admin', 'e10adc3949ba59abbe56e057f20f883e', 1, NULL);

INSERT INTO xxl_job_lock (lock_name)
VALUES ('schedule_lock');

-- 固定种子ID写入后同步 identity sequence
SELECT setval(pg_get_serial_sequence('xxl_job_group', 'id')::regclass,
              (SELECT max(id) FROM xxl_job_group), true);
SELECT setval(pg_get_serial_sequence('xxl_job_info', 'id')::regclass,
              (SELECT max(id) FROM xxl_job_info), true);
SELECT setval(pg_get_serial_sequence('xxl_job_user', 'id')::regclass,
              (SELECT max(id) FROM xxl_job_user), true);

COMMIT;
-- 报错时执行：ROLLBACK;
